@web_HostAddress = http://localhost:5000

### Test the Robot Movement Endpoint

POST {{web_HostAddress}}/tibber-developer-test/enter-path
Content-Type: application/json
Accept: application/json

{
  "start": {
    "x": 10,
    "y": 22
  },
  "commands": [
    {
      "direction": "east",
      "steps": 2
    },
    {
      "direction": "north",
      "steps": 1
    }
  ]
}
